joint_state_topic: "/joint_states"
target_position_topic: '/target_position_topic'
gripper_state_topic: '/gripper_state_topic'
cube_pose_topic: /cube_pose_topic'
pick_toggle_topic: /pick_toggle_topic'
ee_control_service_name: '/ee_control_service_name'